name: Build Java App

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  package-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file java-app/pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          path: java-app/target/*.jar
      - name: Publish the artifact
        run: mvn deploy --file java-app/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}