name: Greetings

on: [pull_request_target, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting-log:
    name: Log Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Log Greeting
        run: echo "Hello World"
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v2.0.0
        with:
          issue-message: "Hello World"
          pr-message: "Hello World"